artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://github.com/shubhamaware18/datasets/raw/main/samsumdata.zip"
  load_data_fil: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion